SET vG.HomeContainer='lib://10.1.Rinats_Sabirovs';

$(Include=$(vG.HomeContainer)\InitLink.qvs);

Test_Git:
LOAD
    Serial_No,
    Cleaning_Session_Last_Date,
    Firmware_Last
FROM 
[$(vG.QVDPath)Data_Firmware.qvd]
(qvd);

TEST:
LOAD * INLINE [
    Field1,Field2
    TEST1, TEST2
];

TEST_2:
LOAD * INLINE [
    Field1,Field23
    TEST1, TEST243
    TESTr21, TESTr2
];

//fwjhflwjhefliwjf


//shflnsd fsldnfsdfas